# Generated by Django 4.0.4 on 2022-05-12 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_category', models.CharField(max_length=32, null=True)),
                ('post_title', models.CharField(max_length=256)),
                ('post_content', models.TextField()),
                ('post_viewnum', models.IntegerField(default=0)),
                ('like_num', models.IntegerField(default=0)),
                ('post_wdate', models.DateTimeField(auto_now_add=True)),
                ('post_mdate', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
