# Generated by Django 4.0.4 on 2022-05-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
