# Generated by Django 4.0.4 on 2022-05-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
