# Generated by Django 4.0.4 on 2022-05-15 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0005_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='post/')),
                ('post_content', models.TextField()),
                ('post_viewnum', models.IntegerField(default=0)),
                ('like_num', models.IntegerField(default=0)),
                ('post_wdate', models.DateTimeField(auto_now_add=True)),
                ('post_mdate', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
