# Generated by Django 4.0.4 on 2022-05-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
