# Generated by Django 4.0.4 on 2022-05-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_mdate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_wdate',
        ),
    ]
