# Generated by Django 4.0.4 on 2022-05-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0009_remove_post_post_mdate_remove_post_post_wdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
