# Generated by Django 4.0.4 on 2022-05-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('post_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_category', models.CharField(max_length=32)),
            ],
        ),
    ]
