# Generated by Django 4.0.4 on 2022-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_language', models.CharField(max_length=32)),
                ('code_content', models.TextField()),
                ('code_result', models.TextField()),
                ('practice_chnum', models.IntegerField()),
                ('code_source', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
