# Generated by Django 4.0.4 on 2022-05-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
