# Generated by Django 4.0.4 on 2022-05-24 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('practice_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_content', models.TextField()),
                ('code_result', models.TextField()),
                ('practice_chnum', models.IntegerField()),
                ('code_source', models.CharField(max_length=256, null=True)),
                ('code_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_code', to='practiceapp.language')),
            ],
        ),
    ]
