# Generated by Django 4.0.4 on 2022-05-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0005_presult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presult',
        ),
    ]
