# Generated by Django 4.0.5 on 2022-06-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upracticeapp', '0002_delete_upractice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upractice',
            fields=[
                ('upractice_id', models.AutoField(primary_key=True, serialize=False)),
                ('upractice_title', models.CharField(max_length=32)),
                ('upractice_content', models.TextField()),
                ('upractice_result', models.TextField()),
                ('upractice_chnum', models.IntegerField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
